"""identity domain tables

Revision ID: 5c20a2e16602
Revises: ee86634ae2bd
Create Date: 2026-07-05 14:31:00.088348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c20a2e16602'
down_revision = 'ee86634ae2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS tenant")

    op.create_table('permissions',
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('module', 'action', name='uq_permission_module_action'),
    schema='tenant'
    )
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_code'),
    schema='tenant'
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    schema='tenant'
    )
    op.create_table('auth_sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tenant.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    schema='tenant'
    )
    with op.batch_alter_table('auth_sessions', schema='tenant') as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_auth_sessions_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_auth_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['tenant.permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['tenant.roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='tenant'
    )
    op.create_table('shop_users',
    sa.Column('shop_user_id', sa.UUID(), nullable=False),
    sa.Column('shop_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['tenant.users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['tenant.roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tenant.users.user_id'], ),
    sa.PrimaryKeyConstraint('shop_user_id'),
    sa.UniqueConstraint('shop_id', 'user_id', name='uq_shop_user'),
    schema='tenant'
    )
    with op.batch_alter_table('shop_users', schema='tenant') as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_shop_users_invited_by'), ['invited_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_shop_users_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_shop_users_shop_id'), ['shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_shop_users_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_users', schema='tenant') as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_shop_users_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_shop_users_shop_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_shop_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_shop_users_invited_by'))

    op.drop_table('shop_users', schema='tenant')
    op.drop_table('role_permissions', schema='tenant')
    with op.batch_alter_table('auth_sessions', schema='tenant') as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_auth_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_auth_sessions_shop_id'))

    op.drop_table('auth_sessions', schema='tenant')
    op.drop_table('users', schema='tenant')
    op.drop_table('roles', schema='tenant')
    op.drop_table('permissions', schema='tenant')

    op.execute("DROP SCHEMA IF EXISTS tenant")
    # ### end Alembic commands ###
