"""shop profile fields

Revision ID: 64772e9c10b5
Revises: 7ec80ef4800e
Create Date: 2026-05-28 00:35:23.340790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64772e9c10b5'
down_revision = '7ec80ef4800e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gst_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('business_type')
        batch_op.drop_column('gst_number')

    # ### end Alembic commands ###
